[package]
name = "femtovg"
description = "Antialiased 2D vector drawing library"
version = "0.1.0"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>", "Adam Nemecek <adamnemecek@gmail.com>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/femtovg/femtovg"
edition = "2018"

[profile.release]
debug = true

[dependencies]
fnv = "1.0.7"
rgb = "0.8.20"
imgref = "1.6.1"
bitflags = "1.2.1"
owned_ttf_parser = "0.6.0"
rustybuzz = "0.3.0"
unicode-bidi = "0.3.4"
unicode-segmentation = "1.6.0"
generational-arena = "0.2.8"
lru = { version = "0.5.3", default-features = false }
image = { version = "0.23.6", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
glow = { version = "0.6.1", default-features = false }

[features]
default = ["image-loading"]
image-loading = ["image"]

[dev-dependencies]
glutin = "0.24.1"
euclid = "0.20.13"
rand = "0.7"
svg = "0.8.0"
usvg = "0.12.0"
